---
- hosts: ubuntu-client
  vars_files:
    - vars/default.yaml
  tasks:
    - name: create DBs 
      mysql_db:
        name: insia
        state: present
        login_user: root
        login_password: "{{ mysql_root_password }}"
