---
- hosts: ubuntu-client 
  become: yes
  vars_files:
    - vars/default.yaml
  tasks:
    - name: Ensure mysql is running and starts on boot
      service:
        name: mysql
        state: started
        enabled: yes
      become: yes

    - name: Create `/root/.my.cnf`  with root password credentials
      template:
        src:  my.cnf
        dest: /root/.my.cnf
        owner: root
        mode: 0600
      become: yes
      notify: Restart MySQL


    - name: Ensure mysql root password is updated for all root accounts
      mysql_user:
        name: root
        host: "localhost"
        login_unix_socket: /var/run/mysqld/mysqld.sock
        password: "{{ mysql_root_password }}"
        priv: '*.*:ALL,GRANT'
        check_implicit_admin: true
      become: yes
      notify: Restart MySQL
  handlers:
    - name: Restart MySQL
      service: name=mysql state=restarted
   
